name: Build Extension on Commit

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./src/fontend/package-lock.json

      - name: Install dependencies
        working-directory: ./src/frontend
        run: npm ci

      - name: Build extension
        working-directory: ./src/frontend
        run: npm run build

      - name: Zip the build folder
        run: |
          cd src/Frontend
          zip -r ../../build.zip dist/*

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: contest-reminder-build
          path: build.zip
