name: Upload Extension Build

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./src/frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./src/frontend
        run: npm ci

      - name: Build extension
        working-directory: ./src/frontend
        run: npm run build

      - name: Zip the build folder
      
        run: |
          cd src/frontend
          zip -r ../../build.zip dist/*

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
